version: '2'
services:
  web:
    image: nginx
    ports:
      - "8089:80"
    volumes:
      - ./docker/config/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/data
    links: [fpm]

  fpm:
    build: .
    environment:
      APP_ENV: "local"
      GIT_OAUTH_TOKEN: "ec4f2ade0ed38eb8f37661a9fb22167a7296e2fb"
      COMPOSER_CACHE_DIR: /var/data/composer
      XDEBUG_REMOTE_HOST: 192.168.2.71
    volumes:
      - ./:/var/www
      - ./docker/config/local/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/config/local/fpm/php.ini:/usr/local/etc/php/php.ini
      - composer_data:/var/data/composer

volumes:
  composer_data:
    driver: local
